from typing import Optional
from BaseClasses import ItemClassification,Item
class FlipWitchItem(Item):
    def __init__(self, name: str, classification: ItemClassification, code: Optional[int], player: int):
        super().__init__(name, classification, code, player)

class ItemData:
    def __init__(self, id:int, classification: ItemClassification):
        self.classification = classification
        self.id = None if id is None else id + 300000000
        self.table_index = id

item_table = {
    "Mimic Chest Key":1,
    "Ghost Form":2,
    "Black Witch Costume":3,
    "Fortune Cat":4,
    "Ending":5,
    "Sacrificial Dagger":6,
    "Toxic Slime Vial":7,
    "Haunted Scythe":8,
    "Magical Mushroom":9,
    "Goblin Bomb":10,
    "Ring Of The Moon":11,
    "Harpy Feather":12,
    "Disarming Bell":13,
    "Slime Form":14,
    "Slime Sentry":15,
    "Frilly Panties":16,
    "Demonic Cuff":17,
    "Magnetic Hairpin":18,
    "Cursed Talisman":19,
    "Portable Portal":20,
    "Ring Of The Sun":21,
    "Star Bracelet":22,
    "Yellow Frog Talisman":23,
    "Mind Mushroom":24,
    "Heart Necklace":25,
    "Flutterknife Garter":26,
    "Blue Frog Talisman":27,
    "Chaos Key Piece":28,
    "Bewitched Bubble":34,
    "Goblin Crystal":35,
    "Demon Wings":36,
    "Angel Feathers":37,
    "Mermaid Scale":38,
    "Red Wizard Costume":39,
    "Nun Costume":40,
    "Priest Costume":41,
    "Miko Costume":42,
    "Farmer Costume":43,
    "Cat Costume":44,
    "Goblin Costume":45,
    "Maid Costume":46,
    "Pigman Costume":47,
    "Bunny Costume":48,
    "Rat Costume":49,
    "Nurse Costume":50,
    "Angler Costume":51,
    "Dominating Costume":52,
    "Postman Costume":53,
    "Fairy Costume":54,
    "Alchemist Costume":55,
    "Rundown House Key":56,
    "Ghostly Castle Key":57,
    "The Beast's Key":58,
    "Secret Club Door Key":59,
    "Slime Citadel Key":60,
    "Frog Boss Key":61,
    "Goblin Queen Key":62,
    "Rose Garden Key":63,
    "Collapsed Temple Key":64,
    "Demon Boss Key":65,
    "Slimy Sub Boss Key":66,
    "Chaos Sanctum Key":67,
    "Abandoned Apartment Key":68,
    "Secret Garden Key":69,
    "Demon Club Door Key":70,
    "Forgotten Fungal Door Key":71,
    "Slime Boss Key":72,
    "Peachy Peach":73, #11 or 12 upgrades?
    "Gacha Coin":74, #44 of these
    "Gold Coins":75, #Money
    "Progressive Belle Item":76,
    "Momo Server Admin Password":78,
    "Bundle of Clothes":79,
    "Progressive Gobliana Item":80,
    "Progressive Kyoni Item":82,
    "Soul Fragment":84,
    "Legendary Halo":87,
    "Progressive Letter":88,
    "Silky Slime":90,
    "Red Wine":92,
    "Blue Jelly Mushroom":93,
    "Maid Contract":94,
    "Progressive Tatil Item":95,
    "Summon Stone":96,
    "Health Upgrade":99, #10 of these
    "Mana Upgrade":100, #10 of these
    "Wand Upgrade":101,
    "Fairy Bubble":102,
    "Progressive Animal Girl Gacha":110,
    "Progressive Bunny Girl Gacha":120,
    "Progressive Angels & Demons Gacha":130,
    "Progressive Monster Girl Gacha":140,
    "Special Promo Gacha":143,
    "Peachy Peach Upgrade":144,
    "Deed to Fungal Forest":145,

    #junk items
    #"Animal Girl Figure 1":201,
    #"Animal Girl Figure 2":202,
    #"Animal Girl Figure 3":203,
    #"Animal Girl Figure 4":204,
    #"Animal Girl Figure 5":205,
    #"Animal Girl Figure 6":206,
    #"Animal Girl Figure 7":207,
    #"Animal Girl Figure 8":208,
    #"Animal Girl Figure 9":209,
    #"Animal Girl Figure 10":210,
    #"Bunny Girl Figure 1":211,
    #"Bunny Girl Figure 2":212,
    #"Bunny Girl Figure 3":213,
    #"Bunny Girl Figure 4":214,
    #"Bunny Girl Figure 5":215,
    #"Bunny Girl Figure 6":216,
    #"Bunny Girl Figure 7":217,
    #"Bunny Girl Figure 8":218,
    #"Bunny Girl Figure 9":219,
    #"Bunny Girl Figure 10":220,
    #"Angel & Demon Figure 1":221,
    #"Angel & Demon Figure 2":222,
    #"Angel & Demon Figure 3":223,
    #"Angel & Demon Figure 4":224,
    #"Angel & Demon Figure 5":225,
    #"Angel & Demon Figure 6":226,
    #"Angel & Demon Figure 7":227,
    #"Angel & Demon Figure 8":228,
    #"Angel & Demon Figure 9":229,
    #"Angel & Demon Figure 10":230,
    #"Monster Girl Figure 1":231,
    #"Monster Girl Figure 2":232,
    #"Monster Girl Figure 3":233,
    #"Monster Girl Figure 4":234,
    #"Monster Girl Figure 5":235,
    #"Monster Girl Figure 6":236,
    #"Monster Girl Figure 7":237,
    #"Monster Girl Figure 8":238,
    #"Monster Girl Figure 9":239,
    #"Monster Girl Figure 10":240,
    #"Special Promo Figure":241,
#}
#
#quest_table = {
    "Completed Quests":3001,
    "Belle 1":3002,
    "Belle 2":3003,
    "Belle 3":3004,
    "Goblin 1":3005,
    "Goblin 2":3006,
    "Rover 1":3007,
    "Rover 2":3008,
    "Rover 3":3009,
    "Merchant 1":3010,
    "Milk & Cream 1":3011,
    "Milk & Cream 2":3012,
    "Milk & Cream 3":3013,
    "Janic 1":3014,
    "Janic 2":3015,
    "Kyoni 1":3016,
}
