from BaseClasses import Location
import typing

class FlipWitchLocation(Location):
    game: str = "FlipWitch"

    def __init__(self, player:int, name:str, address:typing.Optional[int], parent):
        super().__init__(player, name, address, parent)
        self.event=not address

location_table = {
    "Sensei's Hut, Navy Witch Costume Chest":1,
    "Sensei's Hut, Red Wizard Costume Chest":2,
    "Beatrix: Magical Mentor":3,
    "WW Past the Hut":4,
    "Ending":5,
    "WW Genesis Coin":6,
    "WW Special Promotion":7,
    "WW Belle: Need My Cowbell":8,
    "WW Rundown House Save Hidden Chest":9,
    "WW Red Wine Chest":10,
    "WW Mimic Chest Key Room Chest 1":183,
    "WW Mimic Chest Key Room Chest 2":184,
    "WW Secret Cave Coin":11,
    "WW Secret Cave Chest":12,
    "WW Mimi Hidden Chest":13,
    "WW Mimi: Giant Chest Key":14,
    "WW Goblin Apartment":15,
    "WW Secret Alcove":16,
    "WW Belle's Cowbell":17,
    "WW Ruined House Chest":18,
    "WW Ruined House Coin":19,
    "WW Before Great Fairy":20,
    "WW Man Cave":21,
    "WW Past Man Cave":22,
    "WW Gerry G. Atric":23,
    "WW Hidden Alcove":24,
    "WW Beside Flip Platform":25,
    "WW Gobliana: Goblin Headshot":26,
    "WW Gobliana: A Model Goblin":27,
    "WW After Chaos Fight":28,
    "WW Boss Key Room Big Chest":29,
    "WW Boss Key Room Chest":30,
    "WW Boss Key Room HP Upgrade":31,
    "WW Goblin Queen Chaos Key Piece":32,
    "WW Goblin Queen MP Upgrade":33,
    "WW Goblin Princess: Goblin Stud":185,
    "WW Post Fight":186,
    "WW Flying Fairy: Fairy Mushrooms":34,
    "WW Flying Fairy Chest":35,
    "WW Hidden Spring Room":36,
    "WW Quest Upgrade 1":37,
    "WW Quest Upgrade 2":38,
    "WW Quest Upgrade 3":39,
    "WW Quest Upgrade 4":40,
    "WW Quest Upgrade 5":41,
    "WW Quest Upgrade 6":42,
    "WW Quest Upgrade 7":43,
    "WW Quest Upgrade 8":44,
    "WW Quest Upgrade 9":45,
    "WW Quest Upgrade 10":46,
    "WW Great Fairy":47,
    "City Toilets HP Upgrade":48,
    "City Toilets MP Upgrade":49,
    "City Toilets Coin":50,
    "City Cabaret Cafe Girls Room Chest":51,
    "City Cabaret Cafe: Boned":52,
    "City Cabaret Cafe: Legendary Chewtoy":53,
    "City Cabaret Cafe Delicious Milk":54,
    "City Cabaret Cafe: Deluxe Milkshake":55,
    "City Cabaret Cafe Cherry Apartment Key":56,
    "City Cabaret Cafe: Rat Problem":57,
    "City Cabaret Cafe: Ghost Hunters":58,
    "City Cabaret Cafe: Haunted Bathroom":59,
    "City Cabaret Cafe: Ectogasm":60,
    "City Cabaret Cafe: Jelly Mushroom":61,
    "City Cabaret Cafe: Booze Bunny":62,
    "City Cabaret Cafe: Help Wanted":63,
    "City Cabaret Cafe VIP Chest":64,
    "City Unmarked House Fairy Bubble":65,
    "City Shop Item 1":66,
    "City Shop Item 2":67,
    "City Shop Item 3":68,
    "City Shop Item 4":69,
    "City Shop Roof Chest":70,
    "City Fashion Shop 1":71,
    "City Fashion Shop 2":72,
    "City Clinic: Medical Emergency":73,
    "City Rover: Let the Dog Out":74,
    "City Ancient Being Chest":75,
    "City Ancient Being: Stop Democracy":76,
    "City Ghostly Castle Key Chest":77,
    "City Below Cemetary":78,
    "City Chaos Fight":79,
    "City Bunny Club: The Bunny Club":80,
    "City Bunny Club: Find the Silky Slime":81,
    "City Leg's Office Goblin Apartment Key":82,
    "City Leg's Office: Emotional Baggage":83,
    "City Leg's Office: Dirty Debut":84,
    "City Kyoni's Shop: Belle's Milkshake":85,
    "City Kyoni's Shop: Devilicious":86,
    "City Kyoni's Shop: What's a Daikon?":87,
    "City Dusty: Alley Cat":88,
    "City Cult of Whorus: Priestess of Whorus":89,
    "City Cult of Whorus: A Priest's Duties":90,
    "City MomoRobo Server Password":91,
    "City MomoRobo Out of Service":92,
    "City MomoRobo Girl's Gallery":248,
    "City MomoRobo Boy's Gallery":249,
    "City Banana Apartment":250,
    "City Behind Alley":93,
    "City Animal Girls Gacha 1":94,
    "City Animal Girls Gacha 2":95,
    "City Animal Girls Gacha 3":96,
    "City Animal Girls Gacha 4":97,
    "City Animal Girls Gacha 5":98,
    "City Animal Girls Gacha 6":99,
    "City Animal Girls Gacha 7":100,
    "City Animal Girls Gacha 8":101,
    "City Animal Girls Gacha 9":102,
    "City Animal Girls Gacha 10":103,
    "City Bunny Girls Gacha 1":104,
    "City Bunny Girls Gacha 2":105,
    "City Bunny Girls Gacha 3":106,
    "City Bunny Girls Gacha 4":107,
    "City Bunny Girls Gacha 5":108,
    "City Bunny Girls Gacha 6":109,
    "City Bunny Girls Gacha 7":110,
    "City Bunny Girls Gacha 8":111,
    "City Bunny Girls Gacha 9":112,
    "City Bunny Girls Gacha 10":113,
    "City Angels And Demons Gacha 1":114,
    "City Angels And Demons Gacha 2":115,
    "City Angels And Demons Gacha 3":116,
    "City Angels And Demons Gacha 4":117,
    "City Angels And Demons Gacha 5":118,
    "City Angels And Demons Gacha 6":119,
    "City Angels And Demons Gacha 7":120,
    "City Angels And Demons Gacha 8":121,
    "City Angels And Demons Gacha 9":122,
    "City Angels And Demons Gacha 10":123,
    "City Monster Girls Gacha 1":124,
    "City Monster Girls Gacha 2":125,
    "City Monster Girls Gacha 3":126,
    "City Monster Girls Gacha 4":127,
    "City Monster Girls Gacha 5":128,
    "City Monster Girls Gacha 6":129,
    "City Monster Girls Gacha 7":130,
    "City Monster Girls Gacha 8":131,
    "City Monster Girls Gacha 9":132,
    "City Monster Girls Gacha 10":133,
    "City Abandoned Homes 02 House Chest":134,
    "City Abandoned Homes 01 House Coin":135,
    "City Abandoned Homes 6 House Coin":136,
    "City Abandoned Homes Green House Chest":137,
    "City Lone House Chest":138,
    "City Pig Mansion Fungal Key":139,
    "City Pig Mansion: Tatil's Tale":140,
    "City Pig Mansion Maid Contract":141,
    "City Pig Mansion: Signing Bonus":142,
    "SS Hidden Pipe Chest":143,
    "SS Side Room Coin":144,
    "SS Side Room Chest":145,
    "SS Ratchel Coin":146,
    "SS Ratchel: Cardio Day":147,
    "SS Rat Costume Chest 1":148,
    "SS Rat Costume Chest 2":149,
    "SS Rat Costume Chest 3":150,
    "SS Shady Gauntlet HP Upgrade":151,
    "SS Shady Gauntlet Chest":152,
    "SS Elf Merchant Item 1":153,
    "SS Elf Merchant Item 2":154,
    "SS Elf Merchant Chest":332,
    "SS Dr. Witch Doctor Big Chest":155,
    "SS Dr. Witch Doctor MP Upgrade":156,
    "SS Dr. Witch Doctor Tutorial Chest":157,
    "GC Below Entrance Chest":158,
    "GC Slime Form Room Chest 1":159,
    "GC Slime Form Room Chest 2":160,
    "GC Slime Form Room Chest 3":161,
    "GC Giant Room, Flip Magic Platform":162,
    "GC Giant Room, Blind Jump Coin":163,
    "GC Up the Ladder":164,
    "GC Hidden Ledge":165,
    "GC Milk & Cream: Panty Raid":166,
    "GC Elf Merchant Item":167,
    "GC Elf Merchant Chest":168,
    "GC Secret Garden Key Chest":169,
    "GC Hidden Wall":170,
    "GC Along the Path":171,
    "GC Hidden Spring Room":172,
    "GC Behind the Vines":173,
    "GC Across the Boss Room":174,
    "GC Hidden Shrub":175,
    "GC Ghost Form Chest":176,
    "GC Thimble Costume 1":177,
    "GC Thimble Costume 2":178,
    "GC Thimble Chest":179,
    "GC Willow The Whiff":180,
    "GC Ghost Boss Chaos Key Piece":181,
    "GC Ghost Boss MP Upgrade":182,
    "GC Ghostly Gauntlet":240,
    "JG Hidden Flip Magic Room":187,
    "JG Slime Form Room":188,
    "JG Early Ledge":189,
    "JG Secret Spring Room Chest":190,
    "JG Secret Spring Room Coin":191,
    "JG Nearby Cat Shrine":192,
    "JG Unlucky Cat Statue: Unlucky Cat":193,
    "JG Beast Key Chest":194,
    "JG Hidden Ledge":195,
    "JG Annahell: Harvest Season":196,
    "JG Annahell Chest":197,
    "JG Hidden Hole":198,
    "JG Near Elf Merchant":199,
    "JG Elf Merchant Item 1":200,
    "JG Elf Merchant Item 2":201,
    "JG Hot Guy Chest":202,
    "JG Far Ledge":203,
    "JG Hidden Flip Magic Ledge Chest":204,
    "JG Demon Wings Chest":205,
    "JG Demon Wings Tutorial":206,
    "JG Northern Cat Shrine: Cat Shrine":207,
    "JG Northern Cat Shrine Chest":208,
    "JG Northern Cat Shrine Coin":209,
    "CD Club Demon Entrance":210,
    "CD Under The Table":211,
    "CD Bad Boy: Demon Letter":212,
    "CD Club Door Room":213,
    "CD Flip Magic Chest":214,
    "CD Flip Magic Coin":215,
    "CD Thimble Costume 1":216,
    "CD Thimble Costume 2":217,
    "CD Demonic Gauntlet":218,
    "CD Club Key Room Chest":219,
    "CD Club Key Room Coin":220,
    "CD Cat Shrine":221,
    "CD Demon Boss Key Chest":222,
    "CD Demon Boss Chaos Key Piece":223,
    "CD Demon Boss MP Upgrade":224,
    "TG Early Gacha Coin":225,
    "TG Early Coins Chest":226,
    "TG Hidden Foliage":227,
    "TG Hidden Flip Magic Spring":228,
    "TG Birby":333,
    "TG Flip Magic Chest":229,
    "TG Hidden Ledge":230,
    "TG Secret Alcove":231,
    "AH Starting Coins":232,
    "AH Hidden Foliage 1":233,
    "AH Hidden Foliage 2":234,
    "AH Elf Merchant Item 1":235,
    "AH Elf Merchant Item 2":236,
    "AH Elf Merchant Chest":237,
    "AH Cloudia":238,
    "AH Angelic Gauntlet":239,
    "AH Thimble Costume 1":241,
    "AH Thimble Costume 2":242,
    "AH Thimble Chest":243,
    "AH Below Thimble":244,
    "AH Gabrielle: Angel Letter":245,
    "AH Gabrielle: Long Distance Relationship":246,
    "AH Gabrielle Chest":247,
    "AH Behind The Vines":251,
    "AH Flip Magic Room":252,
    "AH Angel Feathers Chest":253,
    "AH Below Boss Room Chest":254,
    "AH Below Boss Room Coin":255,
    "AH Angelica Chaos Key Piece":256,
    "AH Angelica MP Upgrade":257,
    "FF Thimble Costume 1":258,
    "FF Thimble Costume 2":259,
    "FF Lower Pit":260,
    "FF Flip Magic Coin":261,
    "FF Fungella: Fungal Deal":262,
    "FF Past Fungella":263,
    "FF Heavenly Daikon Coin":264,
    "FF Past Chaos Fight":265,
    "FF Closed Off Coins":266,
    "FF Between The Thorns":267,
    "FF Elf Merchant Item 1":268,
    "FF Elf Merchant Item 2":269,
    "FF Elf Merchant Chest":270,
    "FF Guarded by Mushrooms":271,
    "FF Fungal Gauntlet":272,
    "FF Blue Jelly Mushroom Chest":273,
    "FF Fungal Door Key Chest":274,
    "FF Secret Fungus Room":275,
    "FF Slime Form Chest":276,
    "FF Slime Citadel Key Chest":277,
    "SC Citadel Entrance":278,
    "SC Secret Room":279,
    "SC Lone Room":280,
    "SC Silky Slime Chest":281,
    "SC Silky Slime Summoning Stone":282,
    "SC Small Detour":283,
    "SC Slimy Sub Boss Key Chest":284,
    "SC Across the Key":285,
    "SC Thimble Costume 1":286,
    "SC Thimble Costume 2":287,
    "SC Slimy Gauntlet":288,
    "SC Near Stone Chest":289,
    "SC Secret Room Past Spring Coin":290,
    "SC Secret Room Past Spring Summoning Stone":291,
    "SC Hidden Tunnel":292,
    "SC Elf Merchant Item 1":293,
    "SC Elf Merchant Item 2":294,
    "SC Slurp, Slime Boss Key Chest":295,
    "SC Slurp, Summoning Stone":296,
    "SC Natasha: Summoning Stones":297,
    "SC Slimy Princess Chaos Key Piece":298,
    "SC Slimy Princess MP Upgrade":299,
    "UU Early Gacha Coin":300,
    "UU Save Coin Chest":301,
    "UU Angler Costume Chest":302,
    "UU Flip Magic Room Chest":303,
    "UU Far Corner":304,
    "UU Sacrificial Dagger Chest":305,
    "UU Flip Magic Room 2 Coin":306,
    "UU Mermaid's Chest":307,
    "UU Chaos Fight Chest":308,
    "UU Above Save Room":309,
    "UU Path to Octrina":310,
    "UU Octrina Chest":311,
    "UU Watery Gauntlet":312,
    "UU Path Near Frog Boss":313,
    "UU Keroku: Seamen, With an A":314,
    "UU Frog Boss Chaos Key Piece":315,
    "UU Frog Boss MP Upgrade":316,
    "CC Outside Castle Coin":317,
    "CC Early Coins Chest":318,
    "CC Goblin/Fungal Path Coin":319,
    "CC Ghost Castle Path Coin":320,
    "CC Jigoku Path Chest":321,
    "CC Near Chaos Sanctum":322,
    "CC Elf Merchant Item 1":323,
    "CC Elf Merchant Chest":324,
    "CC Slime Citadel Path Chest":325,
    "CC Fungal Area Coin":326,
    "CC Big Jump HP Upgrade":327,
    "CC Big Jump Chest":328,
    "CC Pandora Chaos Sanctum Key":329,
    "CC Pandora MP Upgrade":330,
    "CC Chaos Queen":331,

    "Belle 1 Complete Flag":2001,
    "Belle 2 Complete Flag":2002,
    "Belle 3 Complete Flag":2003,
    "Goblin 1 Complete Flag":2004,
    "Goblin 2 Complete Flag":2005,
    "Rover 1 Complete Flag":2006,
    "Rover 2 Complete Flag":2007,
    "Rover 3 Complete Flag":2008,
    "Merchant 1 Complete Flag":2009,
    "Milk & Cream 1 Complete Flag":2010,
    "Milk & Cream 2 Complete Flag":2011,
    "Milk & Cream 3 Complete Flag":2012,
    "Janic 1 Complete Flag":2013,
    "Janic 2 Complete Flag":2014,
    "Kyoni 1 Complete Flag":2015,
    "Belle 1 Complete":1001,
    "Belle 2 Complete":1002,
    "Belle 3 Complete":1003,
    "Goblin 1 Complete":1004,
    "Goblin 2 Complete":1005,
    "Rover 1 Complete":1006,
    "Rover 2 Complete":1007,
    "Rover 3 Complete":1008,
    "Merchant 1 Complete":1009,
    "Milk & Cream 1 Complete":1010,
    "Milk & Cream 2 Complete":1011,
    "Milk & Cream 3 Complete":1012,
    "Janic 1 Complete":1013,
    "Janic 2 Complete":1014,
    "Kyoni 1 Complete":1015,
    "Quest 16 Complete":1016,
    "Quest 17 Complete":1017,
    "Quest 18 Complete":1018,
    "Quest 19 Complete":1019,
    "Quest 20 Complete":1020,
    "Quest 21 Complete":1021,
    "Quest 22 Complete":1022,
    "Quest 23 Complete":1023,
    "Quest 24 Complete":1024,
    "Quest 25 Complete":1025,
    "Quest 26 Complete":1026,
    "Quest 27 Complete":1027,
    "Quest 28 Complete":1028,
    "Quest 29 Complete":1029,
    "Quest 30 Complete":1030,
    "Quest 31 Complete":1031,
    "Quest 32 Complete":1032,
    "Quest 33 Complete":1033,
    "Quest 34 Complete":1034,
    "Quest 35 Complete":1035,
    "Quest 36 Complete":1036,
    "Quest 37 Complete":1037,
    "Quest 38 Complete":1038,
    "Quest 39 Complete":1039,
    "Quest 40 Complete":1040,
}